version: '2'
services:
  web:
    image: nginx:1.11.3
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
  foreman:
    image: openjdk:8
    volumes:
      - ./foreman/:/foreman
    command: java -jar /foreman/foreman.jar
